using ProjectEuler.Maths;
using System.Linq;

namespace ProjectEuler.Problems
{
    // Each new term in the Fibonacci sequence is generated by adding the previous two terms.
    // By starting with 1 and 2, the first 10 terms will be:
    // 1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...
    //
    // By considering the terms in the Fibonacci sequence whose values do not exceed four million, 
    // find the sum of the even-valued terms.
    public class Problem2 : IProblem
    {
        public long Solve()
        {
            var fibonacci = new FibonacciList(4000000);
            return fibonacci.Where(i => i % 2 == 0).Sum();
        }
    }
}